// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteUser(arg1:string):Promise<boolean>;

export function Login(arg1:string,arg2:string):Promise<main.LoginResult>;

export function RegisterUser(arg1:string,arg2:string):Promise<boolean>;
